# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, help_text='Image url', null=True),
        ),
    ]
