# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-29 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={'verbose_name': 'NewsUser', 'verbose_name_plural': 'NewsUsers'},
        ),
    ]
